---
title: "Rapport de projet"
author: 
- BRANSOLLE Line,
- GILIBERT Rémy,
- GONÇALVES Hugo,
- MOHAMEDATNI Aya,
- SÉNÉCAILLE Cassandra,
- Triozon Lucas
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: true
    toc_depth: 2
    fig_caption: yes
    keep_md: no
    keep_tex: yes
    template: template.tex
    pandoc_args:
    - --top-level-division="chapter"
    # pas encore utile- --bibliography="references.bib"
    
toc-title: "Table des matièresddd"
coursecode: TE5PR1MI
#csl: iso690-author-date-fr-no-abstract.csl
Acknowledgements:
- Nos plus sincères remerciements vont à notre encadrant pédagogique pour les conseils avisés sur notre travail.
#biblio-style: elsarticle-harv
session: 2023
team: Groupe Écotourisme
Abstract: résume du projet là
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DBI)
library(RMySQL)
conn <- DBI::dbConnect(
  drv = RMySQL::MySQL(),    # database driver à utiliser
  host = "localhost", # parfois: host = "localhost"
  port = 3306,              # le port s'affiche parfois dans l'URL de votre navigateur 
  username = "root", # parfois: user = "root"
  password = "root",  # si pas de mot de passe. mettre: password = ""
  dbname = "ecotourisme",    # nom de votre base
  #unix.sock = "/Applications/MAMP/tmp/mysql/mysql.sock"
)
```

```{sql connection=conn, max.print = 10, tab.cap = "Pays"}
SELECT id
FROM pays
```


# Introduction
Lorsque les vacances approchent, l’envie de quitter la routine quotidienne s'accompagne souvent de la recherche d'une destination idéale. Pour cette étape, plusieurs critères peuvent entrer en compte: le prix, évidemment, mais aussi le moyen de transport, l’hébergement, les activités ou encore l’empreinte carbone.\par
Le tourisme est une activité humaine qui a des impacts multiples et complexes sur l’environnement, l’économie et la société. Selon l’Organisation mondiale du tourisme (OMT), le tourisme international a atteint 1,4 milliard d’arrivées en 2018, soit une croissance de 6 % par rapport à l’année précédente. Cette tendance à la hausse devrait se poursuivre dans les prochaines années, avec une projection de 1,8 milliard d’arrivées en 2030.\par
En effet, face au changement climatique, de plus en plus de personnes souhaitent faire attention à impacter le moins possible l’environnement lors de leurs déplacements. Pendant longtemps, le tourisme a été appréhendé uniquement au niveau de ses retombées économiques. En 2018, la consommation touristique représentait 7,4 % du PIB en France, avec une croissance dynamique, portée principalement par les visiteurs étrangers.\par
Dans le même temps, le secteur engendre de nombreuses pressions sur l'environnement, et en particulier sur le climat. Selon des données, le tourisme génère actuellement 11 % des émissions de gaz à effet de serre en France. À l'heure où le monde ressent l'urgence de prendre des mesures significatives face aux défis environnementaux, le secteur du tourisme émerge comme l'un des contributeurs majeurs aux émissions de gaz à effet de serre.\par
Cependant, il n’existe pas de solution simple et universelle pour concilier tourisme et développement durable. Chaque destination présente des spécificités et des défis qui nécessitent une analyse approfondie et une adaptation permanente. C’est pourquoi nous avons créé Écotourisme, une plateforme en ligne innovante qui propose aux voyageurs une navigation personnalisée et responsable. Écotourisme se positionne comme la réponse à cette quête, prenant en compte une variété de critères, dont le prix, le moyen de transport, et surtout, l'empreinte carbone.\par
Écotourisme a été conçu pour répondre aux trois besoins principaux de nos utilisateurs: la réduction des dépenses, la simplification du processus de voyage, et la promotion de la responsabilité environnementale. Notre projet joue également un rôle de comparateur statistique. En effet, en collectant des données, nous présentons des statistiques couvrant de nombreuses années et divers indicateurs liés à l'économie, à l'écologie et au tourisme. À l'aide de graphiques et d'un score "Ecotourisme" attribué à chaque pays, les utilisateurs ont accès à des données globales, continentales et nationales. De plus, il est possible de comparer les données statistiques entre deux pays et choisir celui qui correspond le mieux à vos attentes et à vos valeurs. Que vous soyez un voyageur économe, un éco-voyageur engagé, ou simplement un passionné soucieux de minimiser son impact sur l'environnement, Écotourisme est votre solution.\par
Ce qui distingue fondamentalement notre plateforme est son approche intégrée. Contrairement à d'autres services qui se concentrent uniquement sur l'aspect économique ou environnemental, Écotourisme fusionne ces deux dimensions pour offrir une solution complète. Ce rapport a pour but de présenter notre projet Écotourisme, une plateforme qui propose aux voyageurs une offre personnalisée et responsable, basée sur des données statistiques et des critères économiques et environnementaux. 

# Sujet

# Base de données

# Développement et outils

# Planning
**Rapport d'Avancement du Projet**

## Introduction
La planification d’un projet demeure un élément crucial pour assurer une progression efficace et la réussite globale. Au cours de cette période, notre équipe s'est concentrée sur la mise en œuvre et le suivi rigoureux d’un plan établi, en prenant en compte les ajustements nécessaires pour répondre aux éventuels défis rencontrés. L'outil MindView a été intégré dans notre processus de planification pour fournir une visualisation claire des tâches et des dépendances. Les diagrammes générés ont été d'une grande valeur pour la communication interne et ont facilité la compréhension des membres de l'équipe sur les différentes phases du projet. Ainsi il nous servira à illustrer ce rapport.

## Global

Au cours des premiers cycles du projet, l'équipe a consacré une attention particulière à plusieurs phases clés, conformément au planning initial. Les activités suivantes ont été menées avec succès, contribuant à l'avancement global du projet:

- **Description du Projet (13 jours):**
Une période substantielle a été allouée à la compréhension approfondie des exigences du projet. Les sessions de brainstorming et les réunions de travail ont permis de définir clairement les objectifs, les livrables attendus, et les attentes des parties prenantes.

- **Modélisation UML (8 jours):**
Dans cette phase, l'équipe a consacré huit jours à la création de modèles UML détaillés. Ces modèles ont servi de fondement conceptuel, facilitant la visualisation des différentes composantes du système et établissant des relations claires entre celles-ci.

- **Élaboration du Canevas (8 jours):**
Une attention particulière a été accordée à l'élaboration du canevas du projet, fournissant une représentation visuelle de l'architecture globale. Cette étape a permis de valider les besoins du projet avant de passer à des phases plus détaillées.

- **Conception MCD/MOD (8 jours):**
Huit jours ont été alloués à la conception du Modèle Conceptuel de Données (MCD) et du Modèle Organisationnel de Données (MOD). Ces modèles ont permis de définir la structure des données et les relations, guidant ainsi le développement ultérieur.

- **Maquettage avec Figma (13 jours):**
Comme décrit plus tôt la phase de maquettage avec Figma a occupé treize jours, pendant lesquels l'équipe a créé des maquettes interactives et visuelles du projet. Ces maquettes ont été utilisées pour obtenir des retours précoces des parties prenantes et ajuster les éléments de conception en conséquence. 
Même si le temps de réalisation en nombre de jour est similaire aux autres tâches, celle-ci nous a demandé un investissement plus important, par la quantité de travail qu'elle représente. Élaborer un diagramme n'est pas comparable à imaginer une dizaine de pages Web, et le résultat a été obtenu par une concentration particulière de tous nos moyens sur cet objectif.
Ainsi comme monter sur l’image plus tôt la mise en place avant codage nous a pris 1 mois complet afin de cerner l’entièreté des enjeux de ce projet. On remarque aussi que l’organisation de notre groupe nous a permis de travailler en différé sur ces taches et ainsi de gagner un temps précieux.

## Partie Base de Données
 
La gestion évolutive de la base de données a été une composante cruciale du développement du projet, consolidant progressivement les données touristiques et économiques pour offrir une expérience riche et complète. Voici un aperçu détaillé des différentes étapes de développement dans la partie base de données:

- **13/09 - 21/09:**
Première Version et Réflexions, Données Touristiques et Pays (8 jours)
Au cours de cette phase initiale, la première version de la base de données a été élaborée, avec un accent particulier sur les données touristiques et les informations essentielles sur chaque pays. Des réflexions approfondies ont orienté la conception initiale pour garantir une fondation solide.
- **21/09 - 30/09:**
Recherche et Ajout de Données Complémentaires, Économie, Écologie et Sûreté, Mise en Place des Clés Étrangères (9 jours)
La base de données a été enrichie par des données complémentaires, notamment des informations sur l'économie, l'écologie et la sûreté des pays. Les clés étrangères ont été soigneusement mises en place pour établir des relations significatives entre les différentes tables.
- **02/10 - 09/10:**
Réflexion et Ajouts Mineurs: PIB/hab, Continents, Emojis (8 jours)
Cette période a été consacrée à des réflexions approfondies, conduisant à des ajouts mineurs mais significatifs tels que le PIB par habitant, la classification par continents et l'introduction d'emojis pour représenter les drapeaux de nos pays afin d’obtenir une expérience utilisateur plus visuelle et intuitive.
- **09/10 - 11/10:**
Fusion des Tables par Thèmes (2 jours)
Une étape importante a été la fusion des tables par thèmes, améliorant ainsi la cohérence et la facilité d'accès aux données. Cette restructuration a contribué à simplifier la gestion de la base de données et à rendre les requêtes plus efficientes.
- **07/11 - 12/11:** Ajout des Données sur les Aéroports et les Routes Aériennes (6 jours)
L'expansion de la base de données a continué avec l'intégration de données sur les aéroports et les routes aériennes. Cette addition a considérablement enrichi le volet logistique du projet, offrant aux utilisateurs des informations détaillées sur les infrastructures aériennes.
Ajout d'Images pour Chaque Pays: La base de données sera étendue pour inclure des images associées à chaque pays, améliorant ainsi l'expérience utilisateur en offrant une représentation visuelle.
Gestion Continue:
En reconnaissance du caractère dynamique de la base de données, une approche agile sera maintenue pour permettre des mises à jour régulières en fonction des besoins changeants du projet écotourisme.

## Carte

- **02/10 - 10/10:**
Première Version (Fond de Carte, Tests) (9 jours)
Durant cette période, l'équipe a concentré ses efforts sur la création de la première version du projet. C'était la première fois que nous approchions cet outil, et la création de cette version initiale visait à explorer les fonctionnalités offertes et à évaluer sa pertinence. Cette étape préliminaire était cruciale pour prendre une décision éclairée sur l'utilisation continue de l'outil, confirmant ainsi notre choix de poursuivre avec amCharts.
- **10/10 - 11/10:**
Comportement au survol (HTML des Mini-Cartes, Tests) (2 jours)
La seconde phase du développement, centrée sur le comportement au survol, s'est basée sur les premiers bandeaux réalisés pour la page pays. En utilisant ces éléments comme référence, l'équipe a rédigé le code HTML derrière l'affichage des mini-cartes au survol, renforçant ainsi la cohérence de l'interface utilisateur.
- **12/10 - 13/10:**
Affichage des Villes, Focus sur un Pays (2 jours)
Ces deux jours ont été consacrés à l'extension des fonctionnalités du projet, notamment l'affichage des villes et la fonction de mise en évidence d'un pays spécifique. Ces ajouts enrichissent l'expérience utilisateur en fournissant des informations détaillées sur les différentes régions.
- **23/10 - 25/10:** 
Réécriture en JS Pur (3 jours)
Une évolution majeure a eu lieu avec la réécriture du code en JavaScript pur. Cette transition vers un fichier séparé permet de réutiliser la carte dans n'importe quelle page souhaitée, anticipant notamment notre future page comparateur. Cette modularité renforce l'efficacité du développement et la maintenance à long terme.
- 25/10: 
Adaptation au Comparateur (Comportement au Clic pour Deux Pays) (1 jour)
Pour rendre le projet plus polyvalent, des ajustements ont été apportés pour permettre le support de deux pays mis en avant au lieu d'un seul. Ces modifications s'alignent avec notre vision d'extension future du projet vers une page comparateur, offrant une expérience utilisateur plus complète.
- **15/12 - 17/12:** 
Réécriture en Orienté Objet + Villes Dynamiques au Clic (3 jours)
Une refonte majeure a été entreprise en adoptant une approche orientée objet. Inspirée par l'architecture POO mise en place pour les graphiques, cette transition améliore la lisibilité du code, favorise la réutilisation des fonctionnalités, et simplifie la gestion des futures évolutions du projet.

## Page Pays/ Monde/ Comparateur
Chaque page, caractérisée par des fonctionnalités graphiques avancées, a fait l'objet d'un travail en binôme, favorisant la collaboration et la génération d'idées innovantes. Initialement planifiées sur une plage de 21 à 41 jours, ces périodes ont été recalculées et étendues jusqu'au 22 décembre en raison de contraintes imprévues. (partiels et difficultés sous-estimées).
Page Pays :
La page pays a été conçue pour offrir une expérience approfondie, avec des graphiques détaillés reflétant diverses données économiques, touristiques et environnementales. 
Page Monde:
La complexité des graphiques de la page Monde, agrégeant des données de multiples pays, a demandé une période étendue pour garantir une représentation précise. 

## Page Comparateur
La page comparateur, mettant en œuvre des graphiques comparatifs entre deux pays, a exigé une période supplémentaire pour perfectionner les interactions utilisateur. L'extension a permis d'affiner les fonctionnalités de comparaison, d'ajuster les détails visuels et de garantir une expérience utilisateur fluide.
Cette recalibration des délais a été nécessaire pour surmonter les challenges techniques inhérents à la mise en œuvre de fonctionnalités graphiques avancées. Malgré l'ajustement des périodes, l'objectif principal a toujours été de fournir des pages robustes, offrant des représentations visuelles précises des données tout en maintenant des performances optimales.

## Pages annexes
La conception et le développement des pages Profil, Inscription, Connexion, About, Catalogue des Pays, ainsi que la Footer/Navbar ont été impactés par les ajustements précédents. Ces pages étaient initialement planifiées entre le 21 novembre et le 3 janvier. Voici un aperçu des tâches à accomplir au cours de cette période:

- **Page Profil (18/12 - 15/01):**
Cette page centrale accueillera les fonctionnalités de gestion de profil utilisateur, offrant une expérience personnalisée. La collaboration en binôme se poursuivra pour intégrer des fonctionnalités avancées et assurer une parfaite harmonie visuelle avec les autres pages.
- **Pages d'Inscription et de Connexion (18/12 - 15/01):**
Ces pages cruciales seront revisitées pour garantir une inscription fluide et une connexion sécurisée. L'extension de la période permettra de prendre en compte les évolutions apportées aux autres parties du site, assurant ainsi une intégration homogène.
- **Page About (18/12 - 15/01):**
La page About bénéficiera également d'ajustements pour refléter les dernières améliorations apportées aux autres pages. La période étendue permettra d'approfondir la présentation du projet, de l'équipe et des objectifs globaux.
- **Catalogue des Pays (18/12 - 15/01):**
La création du catalogue des pays facilitera la navigation à travers les informations, offrant une expérience plus rapide et conviviale. Cette fonctionnalité optimisera la recherche d'informations spécifiques sur les différents pays / continent présents dans la base de données.
- **Footer/Navbar (18/12 - 15/01):**
Le Footer  et la Navbar, seront ajusté pour assurer une navigation intuitive sur l'ensemble du site. Les liens vers les différentes pages, y compris les nouvelles, seront intégrés de manière cohérente.
La période allant du 18 décembre au 15 janvier sera cruciale pour finaliser ces pages, en garantissant une intégration homogène des nouvelles fonctionnalités tout en maintenant une expérience utilisateur fluide et cohérente sur l'ensemble du site. L'approche collaborative en binôme sera maintenue pour maximiser l'efficacité et la créativité dans la réalisation de ces dernières étapes du projet.

## Dernière pages et enjeux cruciaux
 
Au cours de la période s'étendant du 15 janvier au 29 janvier, les efforts de développement seront concentrés sur la création des pages Continent et Calculateur. Parallèlement, un contrôle qualité exhaustif sera effectué sur l'ensemble des pages du site pour garantir une expérience utilisateur homogène. Ces pages ont également été affectées par les ajustements de planning antérieurs.

- **Page Continent (15/01 - 29/01):**
La page Continent  a été conçue pour offrir une expérience approfondie, avec des graphiques détaillés reflétant diverses données économiques, touristiques et environnementales, elle est proche de la page pays. 
- **Page Calculateur (15/01 - 29/01):**
La page Calculateur, réputée pour sa complexité technique, sera spécifiquement développée pendant cette période. Le calcul de l'indice, le contrôle qualité des résultats, et l'ajustement visuel seront les principales priorités. Un travail méticuleux sera effectué pour garantir la précision des calculs.
- **Contrôle Qualité Global (15/01 - 29/01):**
Simultanément au développement des nouvelles pages, un contrôle qualité complet sera réalisé sur l'ensemble du site. Chaque page sera passée en revue pour s'assurer de la cohérence des styles CSS, de la précision des fonctionnalités, et de la fluidité de l'expérience utilisateur. Des ajustements seront apportés si nécessaire.
Cette approche holistique, combinant le développement des nouvelles pages avec un contrôle qualité global, vise à garantir la qualité et la cohérence à tous les niveaux du projet. Les ajustements seront apportés en fonction des résultats du contrôle qualité pour atteindre un produit final répondant aux normes élevées établies par l'équipe. La période du 15 janvier au 29 janvier sera cruciale pour la finalisation réussie de ces étapes.

## Conclusion planning
Nous avons rencontré des défis imprévus, notamment des contraintes de temps dues à la complexité des tâches et des ajustements nécessaires pour garantir la qualité globale d’écotourisme. Chaque membre de l'équipe s'est investi dans des domaines spécifiques (page différente sur fonctionnement de binôme et tache annexe), permettant une approche spécialisée et une meilleure efficacité. La collaboration en binôme a renforcé la créativité et la résolution de problèmes, favorisant ainsi des résultats innovants. À l'approche de la phase finale du projet, nous restons résolus à surmonter les obstacles restants et à livrer un projet final répondant aux normes élevées que nous avons établies.

# Conclusion
Pour conclure ce rapport, Écotourisme se dresse comme une réponse novatrice aux défis environnementaux posés par l'industrie du tourisme. À l'heure où ce secteur contribue de manière significative aux émissions de gaz à effet de serre, notre plateforme incite à une approche plus responsable du voyage.\par
Notre engagement en faveur d'un tourisme responsable se manifeste à travers une approche intégrée. Écotourisme n'est pas seulement une plateforme économique, mais un écosystème complet où le plaisir du voyage coexiste avec la responsabilité écologique. 
Ce rapport, subdivisé en plusieurs parties clés, témoigne de notre engagement envers la transparence. À travers la présentation des objectifs, de la base de données, du développement, et des outils, nous partageons chaque étape de notre parcours. 
Lors de la conception et du développement de notre plateforme Ecotourisme, certaines contraintes et limitations cruciales ont été prises en compte pour garantir le succès du projet. Ces contraintes et limitations guideront notre équipe tout au long du projet, garantissant que notre plateforme "Ecotourisme" répondra aux normes les plus élevées, tout en restant flexible et innovante dans sa conception et son développement.\par
La section dédiée à l'empreinte carbone souligne l'importance cruciale de comprendre les conséquences environnementales de nos choix de déplacement. En mettant en lumière les émissions de CO2 associées à différents trajets, nous avons souhaité éduquer nos utilisateurs et les inciter à des choix de voyage plus durables.\par
Écotourisme n'est pas simplement une plateforme de voyage, mais une invitation à repenser la manière dont nous explorons le monde. Nous croyons en un avenir où le plaisir du voyage s'aligne avec la préservation de notre planète.\par
Ensemble, avec nos utilisateurs, et la communauté mondiale, nous façonnons un avenir du tourisme plus respectueux, plus vert, et plus durable. Rejoignez-nous dans cette aventure vers un monde où chaque voyage compte, non seulement pour nous, mais aussi pour les générations futures. Voyagez avec conscience. Voyagez avec Écotourisme.